export const Constants = {
  DFInvalidEmail: 'Please enter a valid email',
  DFFallbackMessage:
    'No form fields configured yet. Please add fields in the Form Builder.',
  DFSubmit:'Submit',
  DFTitle:'Generated Form',
  FBTitle: 'Form Builder',
  FBDropdownMessage: 'Select input type',
  FBLabelMessage: 'Enter label value',
  FBLabelPlaceholder: 'Label',
  FBNameMessage: 'Enter name value',
  FBNamePlaceholder: 'Name',
  FBFallBackMessage: 'No fields added yet.',
  FBOptionsMessage: 'Enter Options',
  FBOptionPlaceholder: 'Option',
  FBAddOptionButton: 'Add Option',
  FBOptionsAddedLabel: 'Options added:',
  FBRequiredLabel: 'required',
  FBAddFieldButton: 'Add Field',
  FBSaveFormButton: 'Save Form',
  FBFormFieldsTitle: 'Form Fields',
  FBNoLabelFallback: '(No Label)',
  FBLabelPrefix: 'Label:',
  FBDeleteButton: 'delete',
  FBDeleteButtonTitle: 'Delete field',
  FBLabelRequiredError: 'Label is required',
  FBNameRequiredError: 'Name is required',
  FBNameUniqueError: 'Name must be unique',
  FBOptionsRequiredError: 'Add at least one option',
  FBSaveSuccessMessage: 'Form saved successfully!',
  FBDeleteConfirmMessage: 'Delete field',
  LoginPasswordError: "Password can't be empty",
  LoginInvalidEmail: 'Please enter a valid email',
  LoginErrorMessage: 'Invalid email or password',
};
